app {
    name = "fraud-detection"

    flink {
        amount_threshold = 1000
        time_window_seconds = 60
    }
    kafka{
    bootstrap_servers = "kafka-1:9092,kafka-2:9092,kafka-3:9092"
        consumer {
            topic = "transactions"
            group_id = "fraud-detection"
            auto_offset_reset = "earliest"
        }
        producer {
            topic = "fraud-alerts"
        }
    }
}
